"""GenPPT autonomous design system.

The design system has two layers:
1. DesignConcept — a deck-level design brief generated by LLM analysis of the topic
2. ThemeSpec — a concrete color/type/mood specification derived from the concept

The key change from the old system: instead of keyword-matching 5 preset themes,
the LLM generates a unique design concept per deck, then concrete theme tokens
are derived from that concept.

The old THEME_LIBRARY is retained as a fallback and for variant_seed=0 fast paths.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .models import ThemeSpec


# ── Design Concept (LLM-driven, per-deck) ─────────────────────────────────────

@dataclass(slots=True)
class DesignConcept:
    """A complete deck-level design brief generated by the LLM.

    This is the "design director's brief" — the output of analyzing the topic,
    audience, and content to decide what the deck should look and feel like.
    """
    # Visual metaphor / style direction
    visual_metaphor: str = ""
    style_direction: str = ""  # e.g. "editorial magazine", "data dashboard", "minimalist story"

    # Color system
    primary_hex: str = "#111827"       # main text / ink
    background_hex: str = "#F8FAFC"     # slide background
    accent_hex: str = "#2563EB"         # the ONE accent color
    accent_secondary_hex: str = "#10B981"  # supporting accent for charts/variety
    semantic_colors: dict[str, str] = field(default_factory=lambda: {
        "positive": "#059669",
        "negative": "#DC2626",
        "warning": "#D97706",
        "info": "#2563EB",
    })

    # Typography
    type_scale_ratio: float = 1.333      # modular scale ratio
    base_size_pt: int = 14               # body base size (sensible default, Director overrides)
    max_title_size_pt: int = 44          # largest headline (Director overrides based on context)
    font_family: str = "Microsoft YaHei"
    font_weight_headline: str = "bold"
    font_weight_body: str = "normal"

    # Spatial system
    spacing_mood: str = "normal"         # airy / normal / compact (Director overrides)
    margin_multiplier: float = 0.9       # 1.0 = default margins, <1 = tighter
    asymmetrical: bool = False           # prefer asymmetry?

    # Visual language
    shape_style: str = "sharp"           # sharp / rounded / mixed
    decoration_level: str = "minimal"    # minimal / moderate / rich
    dark_mode_pages: list[int] = field(default_factory=list)  # which pages use dark bg

    # Design principles to emphasize (indices into design_principles.py)
    emphasized_principles: list[str] = field(default_factory=lambda: [
        "one_idea_per_slide",
        "single_accent",
        "whitespace_ratio",
        "contrast_first",
    ])

    # Narrative rhythm: how page layouts should vary across the deck
    page_rhythm_notes: str = ""

    # Raw LLM reasoning
    design_rationale: str = ""

    def to_theme_spec(self) -> ThemeSpec:
        """Convert design concept to a ThemeSpec for backward compatibility."""
        return ThemeSpec(
            name=self.style_direction.replace(" ", "_") or "custom",
            palette=[
                self.primary_hex,
                self.background_hex,
                self.accent_hex,
                self.accent_secondary_hex,
                self.semantic_colors.get("positive", "#059669"),
                self.semantic_colors.get("warning", "#D97706"),
            ],
            font_family=self.font_family,
            mood=self.visual_metaphor or self.style_direction,
            visual_rules=self._derive_visual_rules(),
        )

    def _derive_visual_rules(self) -> list[str]:
        rules = []
        if self.decoration_level == "minimal":
            rules.append("减少装饰元素，让内容和数据说话")
        if self.shape_style == "sharp":
            rules.append("使用锐利边角和几何形状")
        elif self.shape_style == "rounded":
            rules.append("使用圆角面板和柔和过渡")
        if self.asymmetrical:
            rules.append("偏好非对称布局制造视觉节奏")
        if self.spacing_mood == "airy":
            rules.append("大留白，每页聚焦单一判断")
        return rules

    def to_brand_json(self) -> dict[str, str]:
        """Convert to the brand JSON format the Node.js renderer expects."""
        return {
            "bg": self.background_hex.lstrip("#"),
            "surface": _lighten(self.background_hex, 0.08),
            "panel": "#FFFFFF" if self.background_hex.upper() != "#FFFFFF" else "#F0F0F0",
            "ink": self.primary_hex.lstrip("#"),
            "muted": _muted_from(self.primary_hex),
            "line": _line_from(self.background_hex),
            "lineStrong": _line_strong_from(self.background_hex),
            "accent": self.accent_hex.lstrip("#"),
            "accentSoft": _soften(self.accent_hex),
            "blue": self.accent_hex.lstrip("#"),
            "blueSoft": _soften(self.accent_hex),
            "green": self.semantic_colors.get("positive", "059669"),
            "greenSoft": _soften(self.semantic_colors.get("positive", "#059669")),
            "onDark": "#F9FAFB",
            "onDarkSubtle": "#9CA3AF",
            "darkBg": _dark_bg_from(self.primary_hex),
            "darkSurface": _dark_surface_from(self.primary_hex),
        }


# ── LLM-powered design concept generation ─────────────────────────────────────

def _serialize_page_rhythm(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    return str(value) if value else ""

def generate_design_concept(
    topic: str,
    requirements: str,
    tone: str,
    audience: str,
    deck_plan: dict[str, Any] | None = None,
    variant_seed: int = 0,
    llm: Any = None,
) -> DesignConcept:
    """Use the LLM to generate a complete, autonomous design concept for a deck.

    This replaces the old choose_theme() keyword matching. The LLM analyzes the
    topic semantically and makes design decisions based on what would best serve
    the content and audience — not a fixed menu of templates.
    """
    if llm is None:
        raise RuntimeError(
            "无法生成设计概念：未提供LLM客户端。请配置DEEPSEEK_API_KEY、DASHSCOPE_API_KEY或OPENAI_API_KEY环境变量。"
        )

    return _llm_design_concept(topic, requirements, tone, audience, deck_plan, variant_seed, llm)


def _llm_design_concept(
    topic: str,
    requirements: str,
    tone: str,
    audience: str,
    deck_plan: dict[str, Any] | None,
    variant_seed: int,
    llm: Any,
) -> DesignConcept:
    """Call the LLM to generate a full design concept."""
    deck_info = ""
    if deck_plan:
        deck_info = (
            f"\n叙事逻辑: {deck_plan.get('narrative_mode', deck_plan.get('narrative_logic', ''))}"
            f"\n核心主张: {deck_plan.get('core_claim', '')}"
        )

    personality_hints = [
        "偏好现代极简风格，大量留白，单色强调",
        "偏好编辑杂志风格，大标题，不对称布局",
        "偏好数据仪表盘风格，深色背景，卡片式信息",
        "偏好建筑蓝图风格，细线，几何分区，结构感",
        "偏好温暖人文风格，柔和色板，圆角，亲和力",
    ]
    hint = personality_hints[variant_seed % len(personality_hints)]

    import json

    system_prompt = (
        "你是一位PPT设计总监。你为一套演示文稿创建**全局视觉约束**——不是逐页设计。\n"
        "你在 ContentDesign 之后运行——你已拿到 Brief 和 Slides 的页面结构（index + role），据此设计视觉系统。\n\n"
        "## 你的职责边界\n"
        "你定义配色、字体系统、形状哲学、空间基调。这些都是全局约束。\n"
        "PPTDesign Agent 读取你的约束，在约束内做逐页的具体设计。\n"
        "你不会与 PPTDesign 冲突——你是上游约束，它是下游实现。\n\n"
        "## 设计维度\n\n"
        "1. visual_metaphor: 视觉比喻，来自内容本质而非装饰——\n"
        "   技术架构→'建筑蓝图'(结构感、精确)；趋势分析→'编辑杂志'(大标题、节奏)；\n"
        "   品牌叙事→'故事画卷'(情感流动)；数据报告→'仪表盘'(信息密度)。\n"
        "   坏隐喻: 与内容无关的装饰(如财务报告用'星空探索')。\n"
        "2. style_direction: 英文短语，如'modern minimalist''editorial bold'\n"
        "3. 色彩系统:\n"
        "   - primary是主文字色，background是底色，accent是唯一强调色\n"
        "   - 全篇统一色系，不交替深浅背景\n"
        "   - 对比度: 正文(primary vs background)≥7:1, 大标题≥4.5:1, 标注≥3:1, accent vs background ≥3:1\n"
        "   - accent的HSL饱和度≥60%，显著高于其他颜色\n"
        "   - 所有颜色用#RRGGBB格式\n"
        "4. 字体系统(modular scale):\n"
        "   - base_size_pt(10-16pt)是正文字号基准\n"
        "   - type_scale_ratio(1.25~1.618)生成全部层级:\n"
        "     caption = max(base / ratio, 8pt) (标注,硬地板8pt)\n"
        "     body = base (正文)\n"
        "     h3 = base × ratio (小标题)\n"
        "     h2 = base × ratio² (标题)\n"
        "     h1 = min(base × ratio³, max_title_size_pt) (大标题)\n"
        "   - max_title_size_pt(24-52pt)是硬上限\n"
        "5. 空间: airy(演讲型，少信息) vs compact(文档型，密集论证)\n"
        "6. 形状哲学: sharp(技术/数据) vs rounded(品牌/人文)\n"
        "   - minimal_lines_only(极简)是风格中立选项，两种哲学下均可用\n"
        "7. 装饰级别(decoration_level): minimal(数据报告/技术文档类) vs moderate(产品介绍/演讲类，几何装饰增强视觉节奏) vs rich(品牌叙事/发布会类)\n"
        "   - 技术主题建议用moderate而非minimal，几何装饰可以帮助架构图等核心页面更有层次\n"
        "   - 只有纯数据报告或学术论文才用minimal\n"
        "8. 视觉统一性: 全篇统一配色。不交替深浅背景。\n"
        "9. page_rhythm_notes: JSON格式描述视觉节奏编排，字段:\n"
        "   {\"sections\": [{\"pages\": \"1\", \"role\": \"封面冲击\", \"visual\": \"大标题+airy间距\"}, ...], \"transitions\": \"节奏变化说明\"}\n"
        "10. design_rationale: 解释选择理由，必须回链到主题和受众\n\n"
        "## 工具\n"
        "- validate_color_contrast(primary_hex, background_hex, accent_hex): 计算并检查对比度，返回是否全部≥阈值\n"
        "- validate_type_scale(base_size_pt, ratio, max_title_size_pt): 检查字体层级合理性(caption≥8pt, h1≤max, 层级间≥2pt差距)\n"
        "在输出前考虑对比度和字体层级是否合理。\n\n"
        "重要：发挥创造力。每个deck的设计都应该是独特的。"
    )

    user_prompt = (
        f"主题:{topic}\n要求:{requirements}\n语气:{tone}\n受众:{audience}{deck_info}\n"
        f"设计建议方向:{hint}\n"
        "请输出完整的设计概念JSON。"
    )

    schema_hint = json.dumps({
        "visual_metaphor": "数据仪表盘",
        "style_direction": "dark data-driven",
        "primary_hex": "#F8FAFC",
        "background_hex": "#0F172A",
        "accent_hex": "#38BDF8",
        "accent_secondary_hex": "#34D399",
        "semantic_colors": {"positive": "#059669", "negative": "#DC2626", "warning": "#D97706", "info": "#2563EB"},
        "type_scale_ratio": 1.333,
        "base_size_pt": 13,
        "max_title_size_pt": 42,
        "font_family": "Microsoft YaHei",
        "spacing_mood": "airy",
        "margin_multiplier": 1.2,
        "asymmetrical": False,
        "shape_style": "sharp",
        "decoration_level": "minimal",
        "dark_mode_pages": [],
        "emphasized_principles": ["one_idea_per_slide", "single_accent", "whitespace_ratio"],
        "page_rhythm_notes": "全篇统一浅色背景，封面用较大标题建立入口，内容页保持清晰的信息层级，收束页用留白强调结论",
        "design_rationale": "你的设计理由",
    }, ensure_ascii=False)

    # Support both ChatOpenAI (invoke) and GatewayLLMClient (generate_json)
    if hasattr(llm, "generate_json"):
        payload = llm.generate_json(system_prompt, user_prompt, schema_hint)
    elif hasattr(llm, "invoke"):
        from langchain_core.messages import HumanMessage, SystemMessage
        from .llm import _parse_json_content
        response = llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=f"{user_prompt}\n\n请严格输出JSON，不要输出Markdown。\nJSON结构提示：\n{schema_hint}"),
        ])
        payload = _parse_json_content(str(response.content))
    else:
        raise RuntimeError(f"Unsupported LLM type: {type(llm)}")

    sc = payload.get("semantic_colors", {})
    if not isinstance(sc, dict):
        sc = {}

    dark_pages = payload.get("dark_mode_pages", [])
    if isinstance(dark_pages, list):
        dark_pages = [int(i) for i in dark_pages if str(i).isdigit()]
    else:
        dark_pages = []

    return DesignConcept(
        visual_metaphor=str(payload.get("visual_metaphor", "")),
        style_direction=str(payload.get("style_direction", "")),
        primary_hex=_validate_hex(payload.get("primary_hex"), "#111827"),
        background_hex=_validate_hex(payload.get("background_hex"), "#F8FAFC"),
        accent_hex=_validate_hex(payload.get("accent_hex"), "#2563EB"),
        accent_secondary_hex=_validate_hex(payload.get("accent_secondary_hex"), "#10B981"),
        semantic_colors={
            "positive": _validate_hex(sc.get("positive"), "#059669"),
            "negative": _validate_hex(sc.get("negative"), "#DC2626"),
            "warning": _validate_hex(sc.get("warning"), "#D97706"),
            "info": _validate_hex(sc.get("info"), "#2563EB"),
        },
        type_scale_ratio=float(payload.get("type_scale_ratio", 1.333)),
        base_size_pt=int(payload.get("base_size_pt", 13)),
        max_title_size_pt=int(payload.get("max_title_size_pt", 42)),
        font_family=str(payload.get("font_family", "Microsoft YaHei")),
        font_weight_headline=str(payload.get("font_weight_headline", "bold")),
        font_weight_body=str(payload.get("font_weight_body", "normal")),
        spacing_mood=str(payload.get("spacing_mood", "normal")),
        margin_multiplier=float(payload.get("margin_multiplier", 1.0)),
        asymmetrical=bool(payload.get("asymmetrical", False)),
        shape_style=str(payload.get("shape_style", "sharp")),
        decoration_level=str(payload.get("decoration_level", "minimal")),
        dark_mode_pages=dark_pages,
        emphasized_principles=[
            str(p) for p in (payload.get("emphasized_principles") or ["one_idea_per_slide", "single_accent"])
        ],
        page_rhythm_notes=_serialize_page_rhythm(payload.get("page_rhythm_notes", "")),
        design_rationale=str(payload.get("design_rationale", "")),
    )


def validate_design_concept(concept: DesignConcept) -> list[dict[str, str]]:
    """Validate a DesignConcept and return actionable issues.

    Checks: contrast ratio, type scale range, color harmony, spacing bounds.
    Returns list of {severity, field, message} dicts. Empty list = pass.
    """
    issues: list[dict[str, str]] = []

    # Contrast check: primary text vs background
    try:
        pr = _hex_to_rgb_tuple(concept.primary_hex)
        bg = _hex_to_rgb_tuple(concept.background_hex)

        def _luminance(rgb):
            r, g, b = rgb[0] / 255, rgb[1] / 255, rgb[2] / 255
            r = r / 12.92 if r <= 0.03928 else ((r + 0.055) / 1.055) ** 2.4
            g = g / 12.92 if g <= 0.03928 else ((g + 0.055) / 1.055) ** 2.4
            b = b / 12.92 if b <= 0.03928 else ((b + 0.055) / 1.055) ** 2.4
            return 0.2126 * r + 0.7152 * g + 0.0722 * b

        l1, l2 = _luminance(pr), _luminance(bg)
        ratio = (max(l1, l2) + 0.05) / (min(l1, l2) + 0.05)
        if ratio < 3.0:
            issues.append({"severity": "error", "field": "primary_hex/background_hex",
                           "message": f"对比度{ratio:.1f}:1过低，正文不可读"})
        elif ratio < 4.5:
            issues.append({"severity": "warning", "field": "primary_hex/background_hex",
                           "message": f"对比度{ratio:.1f}:1未达AA标准4.5:1"})
    except Exception:
        pass

    # Type scale bounds
    if concept.base_size_pt < 10:
        issues.append({"severity": "warning", "field": "base_size_pt",
                       "message": f"正文字号{concept.base_size_pt}pt偏小，投影场景建议≥14pt"})
    if concept.max_title_size_pt < 28:
        issues.append({"severity": "warning", "field": "max_title_size_pt",
                       "message": f"标题字号{concept.max_title_size_pt}pt偏小"})
    if concept.type_scale_ratio < 1.15 or concept.type_scale_ratio > 1.8:
        issues.append({"severity": "warning", "field": "type_scale_ratio",
                       "message": f"字号比例{concept.type_scale_ratio}超出推荐范围[1.15, 1.8]"})

    # Spacing bounds
    if concept.spacing_mood == "airy" and concept.margin_multiplier < 0.8:
        issues.append({"severity": "info", "field": "margin_multiplier",
                       "message": "airy模式margin过小，留白不足"})
    if concept.spacing_mood == "compact" and concept.margin_multiplier > 1.5:
        issues.append({"severity": "info", "field": "margin_multiplier",
                       "message": "compact模式margin过大，空间浪费"})

    # Accent vs background check (for decorative use)
    try:
        ac = _hex_to_rgb_tuple(concept.accent_hex)
        bg2 = _hex_to_rgb_tuple(concept.background_hex)
        l_ac = _luminance(ac)
        l_bg = _luminance(bg2)
        accent_contrast = (max(l_ac, l_bg) + 0.05) / (min(l_ac, l_bg) + 0.05)
        if accent_contrast < 1.5:
            issues.append({"severity": "warning", "field": "accent_hex",
                           "message": f"强调色与背景对比度{accent_contrast:.1f}:1过低，装饰元素不可见"})
    except Exception:
        pass

    return issues


def _hex_to_rgb_tuple(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


# ── Color utility helpers ─────────────────────────────────────────────────────

def _validate_hex(value: Any, default: str) -> str:
    if not isinstance(value, str):
        return default
    value = value.strip()
    if not value.startswith("#"):
        value = "#" + value
    if len(value) == 7 and all(c in "0123456789ABCDEFabcdef" for c in value[1:]):
        return value.upper()
    return default


def _lighten(hex_color: str, amount: float) -> str:
    """Lighten a hex color by mixing with white."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    r = min(255, int(r + (255 - r) * amount))
    g = min(255, int(g + (255 - g) * amount))
    b = min(255, int(b + (255 - b) * amount))
    return f"{r:02X}{g:02X}{b:02X}"


def _darken(hex_color: str, amount: float) -> str:
    """Darken a hex color by mixing with black."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    r = max(0, int(r * (1 - amount)))
    g = max(0, int(g * (1 - amount)))
    b = max(0, int(b * (1 - amount)))
    return f"{r:02X}{g:02X}{b:02X}"


def _muted_from(ink_hex: str) -> str:
    """Generate a muted text color from the ink color."""
    h = ink_hex.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    # Mix 60% ink with 40% white
    r2 = int(r * 0.55 + 255 * 0.45)
    g2 = int(g * 0.55 + 255 * 0.45)
    b2 = int(b * 0.55 + 255 * 0.45)
    return f"{r2:02X}{g2:02X}{b2:02X}"


def _line_from(bg_hex: str) -> str:
    """Generate a subtle line color from background."""
    h = bg_hex.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    avg = (r + g + b) / 3
    if avg > 128:
        return f"{int(r * 0.85):02X}{int(g * 0.85):02X}{int(b * 0.85):02X}"
    return f"{min(255, int(r * 1.15)):02X}{min(255, int(g * 1.15)):02X}{min(255, int(b * 1.15)):02X}"


def _line_strong_from(bg_hex: str) -> str:
    h = bg_hex.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    avg = (r + g + b) / 3
    if avg > 128:
        return f"{int(r * 0.7):02X}{int(g * 0.7):02X}{int(b * 0.7):02X}"
    return f"{min(255, int(r * 1.3)):02X}{min(255, int(g * 1.3)):02X}{min(255, int(b * 1.3)):02X}"


def _soften(hex_color: str) -> str:
    """Create a very light version of a color for soft backgrounds."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    # Mix 15% color with 85% white
    r2 = int(r * 0.18 + 255 * 0.82)
    g2 = int(g * 0.18 + 255 * 0.82)
    b2 = int(b * 0.18 + 255 * 0.82)
    return f"{r2:02X}{g2:02X}{b2:02X}"


def _dark_bg_from(ink_hex: str) -> str:
    """Generate a dark background that harmonizes with the ink color."""
    h = ink_hex.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    avg = (r + g + b) / 3
    if avg < 50:
        return "0F172A"
    return f"{int(r * 0.08):02X}{int(g * 0.08):02X}{int(b * 0.08):02X}"


def _dark_surface_from(ink_hex: str) -> str:
    h = ink_hex.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"{min(255, int(r * 0.15 + 15)):02X}{min(255, int(g * 0.15 + 15)):02X}{min(255, int(b * 0.15 + 15)):02X}"
